# Use root/example as user/password credentials
version: '3.1'

services:

  web:
    depends_on:
      - mongo
    container_name: "web"
    command: npm run dev
    build: .
    ports:
      - "8080:8080"
    environment:
      #- DATABASE_URL=postgres://postgres:password@postgres:5432/tourney
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: example

    volumes:
      - ./src:/home/node/app/src
      - ./db:/home/node/app/db
      - ./test:/home/node/app/test
      - ./public:/home/node/app/public

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
