var CONSTANTS = {
  DEFAULT_GAME_WIDTH: 800,
  DEFAULT_GAME_HEIGHT: 800,

  DEFAULT_SHIP_RADIUS: 10,
  DEFAULT_SHIP_COLOR: "#0000FF",
  DEFAULT_SHIP_POS: [400, 400],
  DEFAULT_SHIP_DIRECTION: 270,
};
module.exports = CONSTANTS;
